"""
RFC 8032
5.1.5.  Key Generation

    The private key is 32 octets (256 bits, corresponding to b) of
    cryptographically secure random data.  See [RFC4086] for a discussion
    about randomness.

    The 32-byte public key is generated by the following steps.

    1.  Hash the 32-byte private key using SHA-512, storing the digest in
        a 64-octet large buffer, denoted h.  Only the lower 32 bytes are
        used for generating the public key.

    2.  Prune the buffer: The lowest three bits of the first octet are
        cleared, the highest bit of the last octet is cleared, and the
        second highest bit of the last octet is set.

    3.  Interpret the buffer as the little-endian integer, forming a
        secret scalar s.  Perform a fixed-base scalar multiplication
        [s]B.

    4.  The public key A is the encoding of the point [s]B.  First,
        encode the y-coordinate (in the range 0 <= y < p) as a little-
        endian string of 32 octets.  The most significant bit of the
        final octet is always zero.  To form the encoding of the point
        [s]B, copy the least significant bit of the x coordinate to the
        most significant bit of the final octet.  The result is the
        public key.
"""

import hashlib
from functools import lru_cache
from typing import List

from ed25519 import GE, B



@lru_cache
def get_hashed_parts_from_priv(priv: bytes):
    sha512 = hashlib.new("sha512")
    sha512.update(priv)
    hashed = sha512.digest()
    return hashed[:32], hashed[32:]

@lru_cache
def get_prefix_from_priv(priv: bytes):
    _, prefix = get_hashed_parts_from_priv(priv)
    return prefix


@lru_cache
def get_secret_s_from_priv(priv: bytes):
    first, _ = get_hashed_parts_from_priv(priv)
    h = bytearray(first)
    h[0] &= 0b1111_1000  # clear lowest 3 bits of first octet
    h[31] &= 0b0111_1111  # clear highest bit of last octet
    h[31] |= 0b0100_0000  # set second highest bit of last octet

    s = int.from_bytes(h, "little")
    return s


@lru_cache
def get_pub_point_from_priv(priv: bytes) -> GE:
    s = get_secret_s_from_priv(priv)
    return s * B


@lru_cache
def get_pubkey_from_priv(priv: bytes) -> bytes:
    derived_point = get_pub_point_from_priv(priv)
    return derived_point.to_bytes()


def generate_new() -> List[bytes]:
    from secrets import randbits

    priv = randbits(256).to_bytes(32, "big")
    pub = get_pubkey_from_priv(priv)

    return [priv, pub]


if __name__ == "__main__":
    import json
    from pathlib import Path

    solana_keypair = Path.home() / ".config" / "solana" / "id.json"
    with open(solana_keypair, "r") as f:
        keypair = bytearray(json.load(f))
        real_private = keypair[:32]
        real_public = keypair[32:]
        derived_point = get_pub_point_from_priv(bytes(real_private))
        derived_public = derived_point.to_bytes()

        assert bytes(real_public) == bytes(derived_public)
