"""
RFC 8032
5.1.5.  Key Generation

    The private key is 32 octets (256 bits, corresponding to b) of
    cryptographically secure random data.  See [RFC4086] for a discussion
    about randomness.

    The 32-byte public key is generated by the following steps.

    1.  Hash the 32-byte private key using SHA-512, storing the digest in
        a 64-octet large buffer, denoted h.  Only the lower 32 bytes are
        used for generating the public key.

    2.  Prune the buffer: The lowest three bits of the first octet are
        cleared, the highest bit of the last octet is cleared, and the
        second highest bit of the last octet is set.

    3.  Interpret the buffer as the little-endian integer, forming a
        secret scalar s.  Perform a fixed-base scalar multiplication
        [s]B.

    4.  The public key A is the encoding of the point [s]B.  First,
        encode the y-coordinate (in the range 0 <= y < p) as a little-
        endian string of 32 octets.  The most significant bit of the
        final octet is always zero.  To form the encoding of the point
        [s]B, copy the least significant bit of the x coordinate to the
        most significant bit of the final octet.  The result is the
        public key.
"""

import hashlib
from functools import cached_property
from secrets import randbits
from typing import cast

from ..encodings.base58 import Base58Hash
from .ed25519 import GE, B
from .public_key import PublicKey


class PrivateKey(Base58Hash):
    # On production private keys should be handled more carefully!

    @classmethod
    def new(cls):
        return cls(randbits(256).to_bytes(32, "big"))

    @classmethod
    def from_str(cls, val: str) -> "PublicKey":
        return cast(PublicKey, super().from_str(val))

    def __repr__(self) -> str:
        return f"PrivateKey({self.val.hex()})"

    @cached_property
    def hashed_parts(self):
        sha512 = hashlib.new("sha512")
        sha512.update(self.val)
        hashed = sha512.digest()
        return hashed[:32], hashed[32:]

    @cached_property
    def prefix(self):
        _, prefix = self.hashed_parts
        return prefix

    @cached_property
    def secret(self):
        first, _ = self.hashed_parts
        h = bytearray(first)
        h[0] &= 0b1111_1000  # clear lowest 3 bits of first octet
        h[31] &= 0b0111_1111  # clear highest bit of last octet
        h[31] |= 0b0100_0000  # set second highest bit of last octet

        s = int.from_bytes(h, "little")
        return s

    @cached_property
    def public_ge(self) -> GE:
        s = self.secret
        return s * B

    @cached_property
    def public_key(self) -> PublicKey:
        derived_point = self.public_ge
        return PublicKey(derived_point.to_bytes())


if __name__ == "__main__":
    import json
    from pathlib import Path

    solana_keypair = Path.home() / ".config" / "solana" / "id.json"
    with open(solana_keypair, "r") as f:
        keypair = bytearray(json.load(f))
        real_private = keypair[:32]
        real_public = keypair[32:]

        assert bytes(real_public) == PrivateKey(bytes(real_private)).public_key.val
